spring:
  application:
    name: catalog

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  catalog:
    classpath: "/jcpenney_com_ecommerce_sample.csv"
    maxRows: 20000
    delayMs:
      min: 2000
      max: 2500

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/